---
abstract: 'an atomic drop-in replacement for CORE::symlink'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Symlink-Atomic
no_index:
  directory:
    - corpus
requires:
  Exporter: 0
  File::Spec: 0
  File::Temp: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/File-Symlink-Atomic/issues
  repository: git://github.com/doherty/File-Symlink-Atomic.git
version: 0.001
